import { TProject } from './favoriteProjects';

export const MY_PROJECTS: TProject[] = [
    {
        id: 1,
        user_id: 5,
        title: '리액트, 넥스트, 타입스크립트를 자유자재로 다룰 줄 아는 프론트엔드 개발자 2분 모십니다',
        description:
            'React, Next.js 기반의 프론트엔드 개발자 구합니다. SSR/CSR 환경 및 디자인 시스템 등 관심이 많으신 분을 희망합니다.',
        skills: ['React', 'Next'],
        position: ['FE'],
        work_mode: 'online',
        status: 'active',
        due_date: '2025-05-05',
        created_at: '2025-04-13',
        updated_at: '2025-04-13',
    },
    {
        id: 2,
        user_id: 6,
        title: 'Node.js 백엔드 개발자 구합니다',
        description: 'Node.js, Express 기반의 API 서버를 주로 개발하며, PostgreSQL과 AWS 환경 등을 사용할 예정입니다',
        skills: ['Node'],
        work_mode: 'offline',
        position: ['BE'],
        status: 'active',
        due_date: '2025-04-30',
        created_at: '2025-04-12',
        updated_at: '2025-04-12',
    },
    {
        id: 3,
        user_id: 7,
        title: 'UX/UI 디자이너 구합니다',
        description: '사용자 중심의 인터페이스 설계 및 프로토타이핑 도구를 활용해 빠른 MVP 제작도 가능하신 분 구합니다',
        skills: ['Figma'],
        position: ['DI'],
        due_date: '2025-04-20',
        work_mode: 'online',
        status: 'active',
        created_at: '2025-04-07',
        updated_at: '2025-04-07',
    },
    {
        id: 4,
        user_id: 8,
        title: '풀스택 개발자 모십니다',
        description: '프론트부터 백엔드까지 전체 서비스 개발 경험이 있으며, DevOps에도 익숙합니다.',
        skills: ['React', 'Node'],
        position: ['FS', 'FE', 'BE'],
        work_mode: 'online',
        due_date: '2025-05-30',
        status: 'active',
        created_at: '2025-04-05',
        updated_at: '2025-04-05 ',
    },
    {
        id: 5,
        user_id: 9,
        title: 'QA 모십니다',
        description: 'QA 모십니다. 프로젝트 경험이 있으신 분이면 좋습니다.',
        skills: ['Go', 'Figma'],
        work_mode: 'offline',
        position: ['QA'],
        due_date: '2025-04-28',
        status: 'active',
        created_at: '2025-04-03 ',
        updated_at: '2025-04-03 ',
    },
];

export const mockApplicants = [
    {
        id: 1,
        user_id: 1,
        project_id: 1,
        contents: '프로젝트에 관심이 있습니다. 같이 해보고 싶어요!',
        status: 'waiting',
    },
    {
        id: 2,
        user_id: 2,
        project_id: 1,
        contents: '프로젝트 참여 희망합니다.',
        status: 'waiting',
    },
];
